version: 1.1 ({build})

skip_branch_with_pr: true

os:
  - Visual Studio 2017

platform:
  - x64

matrix:
  fast_finish: true  # Stop remaining jobs after a job failure

configuration:
  - Release

clone_folder: C:\CubbyCalc

install:
  - git submodule update --init
  - ps: |
      $env:CMAKE_GENERATOR = "Visual Studio 15 2017 Win64"

before_build:
  - md C:\CubbyCalc\build
  - cd C:\CubbyCalc\build
  - cmake .. -G "%CMAKE_GENERATOR%"

build:
  project: C:\CubbyCalc\build\CubbyCalc.sln
  parallel: true
  verbosity: normal